FROM node:14-alpine as build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM alpine:latest

RUN mkdir /client_build

COPY --from=build /usr/src/app/dist /client_build

VOLUME /client_build