FROM node:14-alpine as build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# FROM alpine:latest

# RUN mkdir /client_build

# COPY --from=build /usr/src/app/dist /client_build

# VOLUME /client_build

FROM nginx:stable-alpine

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf