version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
  build:
    commands:
      - docker-compose -f docker-compose.yml -f docker-compose.build.yml build
  post_build:
    commands:
      - docker-compose -f docker-compose.yml -f docker-compose.build.yml push
      - export COMMIT_ID_VAL="${COMMIT_ID}"
      - sed -i "s/${COMMIT_ID}/$COMMIT_ID_VAL/g" docker-compose.yml
      - cat docker-compose.yml
artifacts:
  files:
    - "docker-compose.override.yml"
    - "docker-compose.yml"
    - "Dockerrun.aws.json"
env:
  exported-variables:
    - COMMIT_ID