services:
  backend:
    build:
      context: ./epfirms-api
      dockerfile: Dockerfile
      target: base
    container_name: epfirms-api
    expose:
      - '4000'
    ports:
      - '4000:4000'
    volumes:
      - './epfirms-api/src:/home/node/api/src'
    command: npm run dev
    depends_on:
      - database
  client:
    build:
      context: ./epfirms-client
      dockerfile: Dockerfile
    container_name: epfirms-client
    expose:
      - '4200'
    ports:
      - '4200:4200'
    volumes:
      - './epfirms-client:/home/node/client'
      - '/home/node/client/node_modules'
    command: ng serve --host 0.0.0.0
  database:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: epfirms-db
    env_file:
      - ./database.env
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - epfirms-db:/var/lib/mysql
volumes:
  epfirms-db: