services:
  server:
    build:
      context: ./epfirms-api
      dockerfile: Dockerfile.prod
      target: base
    container_name: epfirms-api
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm start
  client:
    build:
      context: ./epfirms-client
      dockerfile: Dockerfile.prod
    container_name: epfirms-client
    expose:
      - '4200'
    ports:
      - '4200:4200'