version: '3'
services:
  backend:
    build:
      context: ./epfirms-api
      dockerfile: Dockerfile.prod
      target: base
    container_name: epfirms-api
    image: jaerq/epfirms-server
  client:
    build:
      context: ./epfirms-client
      dockerfile: Dockerfile.prod
    container_name: epfirms-client
    image: jaerq/epfirms-client