services:
  backend:
    restart: always
    image: 005021368988.dkr.ecr.us-east-2.amazonaws.com/epfirms-server
    container_name: epfirms-api
    expose:
      - '4000'
    ports:
      - '4000:4000'
    networks:
      - nginx_network
    env_file:
      - .env
    command: npm start
  client:
    container_name: epfirms-client
    image: 005021368988.dkr.ecr.us-east-2.amazonaws.com/epfirms-client
    expose:
      - '4200'
    ports:
      - '4200:4200'
    networks:
      - nginx_network
    volumes:
      - client_build:/client_build
  proxy: 
    restart: always
    container_name: epfirms-proxy
    depends_on: 
      - client
      - backend
    image: 005021368988.dkr.ecr.us-east-2.amazonaws.com/epfirms-proxy
    ports: 
      - "80:80"
    networks:
      - nginx_network
    volumes:
      - client_build:/usr/share/nginx/html:ro
networks:
  nginx_network:
    driver: bridge
volumes:
  client_build: