# Compose configuration for building/pushing images
services:
  backend:
    build:
      context: ./epfirms-api
      dockerfile: Dockerfile.prod
      target: base
  client:
    build:
      context: ./epfirms-client
      dockerfile: Dockerfile.prod