# Base compose configuration
services:
  backend:
    container_name: epfirms-api
    image: jaerq/epfirms-server:${COMMIT_ID}
    expose:
      - "4000"
    ports:
      - "4000:4000"
    networks:
      - socket
    command: npm start
  client:
    container_name: epfirms-client
    image: jaerq/epfirms-client
  redis:
    image: redis
    networks:
      - socket
    expose:
      - '6379'
networks:
  socket: