# Production compose configuration
services:
  backend:
    restart: always
    env_file:
      - .env
  client:
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - "${EB_LOG_BASE_DIR}/eb-current-app:/var/log/nginx"