# Development compose configuration
services:
  backend:
    build:
      context: ./epfirms-api
      dockerfile: Dockerfile
      target: base
    volumes:
      - './epfirms-api/src:/home/node/api/src'
    depends_on:
      - database
    command: npm run dev
  client:
    build:
      context: ./epfirms-client
      dockerfile: Dockerfile
    expose:
      - '4200'
    ports:
      - '4200:4200'
    networks:
      - socket
    volumes:
      - './epfirms-client:/home/node/client'
      - '/home/node/client/node_modules'
    command: node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --disable-host-check
  database:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: epfirms-db
    env_file:
      - ./database.env
    expose:
      - '3307'
    ports:
      - '3307:3307'
    volumes:
      - epfirms-db:/var/lib/mysql
    networks:
      - socket
volumes:
  epfirms-db: