import { Token } from 'typedi';

export const env = {
  NODE_ENV: new Token<string>('NODE_ENV'),
  SERVER_HOST: new Token<string>('SERVER_HOST'),
  SERVER_PORT: new Token<string>('SERVER_PORT'),
  PORT: new Token<string>('PORT'),
  DB_NAME: new Token<string>('DB_NAME'),
  DB_USERNAME: new Token<string>('DB_USERNAME'),
  DB_PASSWORD: new Token<string>('DB_PASSWORD'),
  DB_HOST: new Token<string>('DB_HOST'),
  DB_PORT: new Token<string>('DB_PORT'),
  JWT_SECRET: new Token<string>('JWT_SECRET'),
  STRIPE_SECRET: new Token<string>('STRIPE_SECRET'),
  STRIPE_PLAN: new Token<string>('STRIPE_PLAN'),
  EMAIL_API_KEY: new Token<string>('EMAIL_API_KEY'),
  EMAIL_DOMAIN: new Token<string>('EMAIL_DOMAIN'),
  AWS_SECRET_KEY: new Token<string>('AWS_SECRET_KEY'),
  AWS_ACCESS_KEY_ID: new Token<string>('AWS_ACCESS_KEY_ID'),
  AWS_REGION: new Token<string>('AWS_REGION'),
  AWS_BUCKET: new Token<string>('AWS_BUCKET'),
  S3_TASK_DOCUMENTS_BUCKET: new Token<string>('S3_TASK_DOCUMENTS_BUCKET'),
  S3_USER_DOCUMENTS_BUCKET: new Token<string>('S3_USER_DOCUMENTS_BUCKET'),
  S3_ENV_FOLDER: new Token<string>('S3_ENV_FOLDER'),
  CLIENT_URL: new Token<string>('CLIENT_URL'),
  REDIS_HOST: new Token<string>('REDIS_HOST'),
  REDIS_PORT: new Token<string>('REDIS_PORT'),
  ALGOLIA_APP_ID: new Token<string>('ALGOLIA_APP_ID'),
  ALGOLIA_API_KEY: new Token<string>('ALGOLIA_API_KEY'),
  ALGOLIA_INDEX_NAME: new Token<string>('ALGOLIA_INDEX_NAME'),
  ALGOLIA_SEARCH_ONLY_API_KEY: new Token<string>('ALGOLIA_SEARCH_ONLY_API_KEY'),
  TEAM_EMAIL_ADDRESS: new Token<string>('TEAM_EMAIL_ADDRESS'),
  TWILIO_ACCOUNT_SID: new Token<string>('TWILIO_ACCOUNT_SID'),
  TWILIO_AUTH_TOKEN: new Token<string>('TWILIO_AUTH_TOKEN'),
  TWILIO_API_KEY_SID: new Token<string>('TWILIO_API_KEY_SID'),
  TWILIO_API_KEY_SECRET: new Token<string>('TWILIO_API_KEY_SECRET'),
  TWILIO_CONVERSATIONS_SERVICE_SID: new Token<string>('TWILIO_CONVERSATIONS_SERVICE_SID'),
  COMMIT_ID: new Token<string>('COMMIT_ID'),
};
