module.exports = (sequelize, { INTEGER, BOOLEAN, FLOAT, STRING }) => {
  const tableName = 'appointee_summary';

  const AppointeeSummary = sequelize.define(
    tableName,
    {
      id: {
        type: INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
      user_id: {
        type: INTEGER,
      },
      executor_1_rank: { type: STRING },
      executor_1_name: { type: STRING },
      executor_1_address: { type: STRING },
      executor_1_phone: { type: STRING },
      executor_2_rank: { type: STRING },
      executor_2_name: { type: STRING },
      executor_2_address: { type: STRING },
      executor_2_phone: { type: STRING },
      executor_3_rank: { type: STRING },
      executor_3_name: { type: STRING },
      executor_3_address: { type: STRING },
      executor_3_phone: { type: STRING },
      executor_4_rank: { type: STRING },
      executor_4_name: { type: STRING },
      executor_4_address: { type: STRING },
      executor_4_phone: { type: STRING },

      trustee_1_rank: { type: STRING },
      trustee_1_name: { type: STRING },
      trustee_1_address: { type: STRING },
      trustee_1_phone: { type: STRING },
      trustee_2_rank: { type: STRING },
      trustee_2_name: { type: STRING },
      trustee_2_address: { type: STRING },
      trustee_2_phone: { type: STRING },
      trustee_3_rank: { type: STRING },
      trustee_3_name: { type: STRING },
      trustee_3_address: { type: STRING },
      trustee_3_phone: { type: STRING },
      trustee_4_rank: { type: STRING },
      trustee_4_name: { type: STRING },
      trustee_4_address: { type: STRING },
      trustee_4_phone: { type: STRING },

      fpoa_1_rank: { type: STRING },
      fpoa_1_name: { type: STRING },
      fpoa_1_address: { type: STRING },
      fpoa_1_phone: { type: STRING },
      fpoa_2_rank: { type: STRING },
      fpoa_2_name: { type: STRING },
      fpoa_2_address: { type: STRING },
      fpoa_2_phone: { type: STRING },
      fpoa_3_rank: { type: STRING },
      fpoa_3_name: { type: STRING },
      fpoa_3_address: { type: STRING },
      fpoa_3_phone: { type: STRING },
      fpoa_4_rank: { type: STRING },
      fpoa_4_name: { type: STRING },
      fpoa_4_address: { type: STRING },
      fpoa_4_phone: { type: STRING },

      mpoa_1_rank: { type: STRING },
      mpoa_1_name: { type: STRING },
      mpoa_1_address: { type: STRING },
      mpoa_1_phone: { type: STRING },
      mpoa_2_rank: { type: STRING },
      mpoa_2_name: { type: STRING },
      mpoa_2_address: { type: STRING },
      mpoa_2_phone: { type: STRING },
      mpoa_3_rank: { type: STRING },
      mpoa_3_name: { type: STRING },
      mpoa_3_address: { type: STRING },
      mpoa_3_phone: { type: STRING },
      mpoa_4_rank: { type: STRING },
      mpoa_4_name: { type: STRING },
      mpoa_4_address: { type: STRING },
      mpoa_4_phone: { type: STRING },
    },
    {
      tableName,
      defaultScope: {
        attributes: { exclude: ['createdAt', 'updatedAt'] },
      },
    },
  );

  return AppointeeSummary;
};
