module.exports = (sequelize, { INTEGER, BOOLEAN, STRING, TEXT, DATE, FLOAT }) => {
  const tableName = 'invoice';

  const Invoice = sequelize.define(
    tableName,
    {
      id: {
        type: INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
      user_id: {
        type: INTEGER,
      },
      firm_id: {
        type: INTEGER,
        allowNull: false,
      },
      matter_id: {
        type: INTEGER,
        allowNull: false,
      },

      // unique invoice id generated by stripe
      invoice_id: {
        type: STRING,
      },
      due_date: {
        type: STRING,
        allowNull: false,
      },
      description: {
        type: STRING,
      },
      // this one will only ever be edited when a webhook from stripe is fufilled
      // 'draft', 'open', 'paid', 'uncollectible', 'void'
      status: {
        type: STRING,
      },
      total: {
        type: INTEGER,
      },
      hosted_invoice_url: {
        type: STRING,
      },
      is_approved: {
        type: BOOLEAN,
        defaultValue: 0,
      },
      is_client_visible: {
        type: BOOLEAN,
        defaultValue: 0,
      },
    },
    {
      tableName,
      defaultScope: {
        attributes: { exclude: ['createdAt', 'updatedAt'] },
      },
    },
  );

  return Invoice;
};
