services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/api/src
    container_name: epfirms-api
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
    depends_on:
      - database
  client:
    build:
      context: ../epfirms-client
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/client/src
    container_name: epfirms-client
    expose:
      - '4200'
    ports:
      - '4200:4200'
    command: npm run start
  database:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: epfirms-db
    environment:
      MYSQL_DATABASE: 'epfirms-dev'
      MYSQL_ROOT_PASSWORD: 'ABoriy78!!'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - epfirms-db:/var/lib/mysql
volumes:
  epfirms-db: