export class ClientSubscription{
    id?: number;
    user_id: number;
    firm_id: number;
    matter_id: number;
    // unique subscription id generated by stripe
    subscription_id: string;
    // the unique customer_id generated by stripe
    customer_id: string;
    // the date that the subscription will charge
    monthly_due_date: Date;
    description: string;
    // this one will only ever be edited when a webhook from stripe is fufilled
    // 'incomplete', 'active', 'past_due', 'unpaid', 'paid', 'canceled', 'incomplete_expired'
    status: string;
    auto_pay: boolean;
    terms: number;
    cancel_at: Date;

    constructor(user_id: number, firm_id: number, matter_id: number, description: string, terms:number){
        this.user_id = user_id;
        this.firm_id = firm_id;
        this.matter_id = matter_id;
        this.subscription_id = "";
        this.customer_id = "";
        this.monthly_due_date = new Date(Date.now() + (1000 * 60 * 60 * 24 * 30));
        this.description = description;
        this.status = "";
        this.terms = terms;

    }
}