export class ClientSubscription{
    id?: number;
    user_id: number;
    firm_id: number;
    matter_id: number;
    // unique subscription id generated by stripe
    subscription_id: string;
    // the unique customer_id generated by stripe
    customer_id: string;
    // the date that the subscription will charge
    monthly_due_date: Date;
    description: string;
    // this one will only ever be edited when a webhook from stripe is fufilled
    // 'incomplete', 'active', 'past_due', 'unpaid', 'paid', 'canceled', 'incomplete_expired'
    status: string;
    auto_pay: boolean;
    terms: number;
    cancel_at: Date;

    // amount that will be charge monthly
    amount : number;

    constructor(user_id: number, firm_id: number, matter_id: number, description: string, terms:number, monthly_due_date: Date, amount: number){
        console.log("creating date", monthly_due_date);
        console.log(typeof(monthly_due_date));
        this.user_id = user_id;
        this.firm_id = firm_id;
        this.matter_id = matter_id;
        this.subscription_id = "";
        this.customer_id = "";
        this.monthly_due_date = monthly_due_date;
        this.description = description;
        this.status = "";
        this.terms = terms;
        this.amount = amount;

        this.cancel_at = new Date(new Date(monthly_due_date).setMonth(monthly_due_date.getMonth() + terms));
    }
}